[game]
profile = 0
profile_to_file = 1
# timer = 2000

[window]
width = 1080
height = 720
fullscreen = 0
fps_cap = 165
vsync = 0
gpu = 1

[world]
cache_chunk_textures = 0
lighting = 1
cache_light_textures = 0
